### ISSUE TITLE
SeqIO.index does not support gzip files

### ISSUE THREAD

**Issue by crosenth** [fhcrc/seqmagick#42]
http://biopython.org/wiki/SeqIO

We should consider an exit message explaining this issue or write to a temporary file because SeqIO.index (annoyingly) does neither.  This affects transform.sort_name and transform.sort_length.

**Comment by peterjc** [comment]
Its a shame this was never reported to Biopython back in 2014, but it was recently - see https://github.com/biopython/biopython/issues/1666 on giving a better error message.

We could actually index ordinary gzip files (I did this on a branch once), but the performance is terrible - see benchmarks on https://blastedbio.blogspot.co.uk/2011/11/bgzf-blocked-bigger-better-gzip.html

**Comment by crosenth** [comment]
Thank you Peter for following up on this Issue pointing this out
