### ISSUE TITLE
how to translate into 6 frames ?

### ISSUE THREAD

**Issue by lmanchon** [fhcrc/seqmagick#46]
-hi,

./seqmagick convert --translate dna2protein test.fasta out.fasta

convert only into 1 frame.
is there option to translate into 6 frames ?

thx

**Comment by matsen** [comment]
I'm afraid that this operation isn't supported by `seqmagick`, and we don't have anything else that does single-in multiple-out, so I don't see it being supported in the future. 

We have liked the EMBOSS tools [getorf](http://emboss.sourceforge.net/apps/cvs/emboss/apps/getorf.html) and [sixpack](http://emboss.sourceforge.net/apps/cvs/emboss/apps/sixpack.html).
