### ISSUE TITLE
push to pypi

### ISSUE THREAD

**Issue by wwood** [fhcrc/seqmagick#51]
Hi,

I'm trying to include seqmagick in the guix package manager, and noticed that the version on pypi was 0.5.0 where the version on github is 0.6.1-dev, and seems to have been that way since April. Would it be possible to release 0.6.2/0.7.0 or push 0.6.1 to pypi please?

Thanks in advance,
ben

**Comment by bcclaywell** [comment]
@wwood Sorry for the delay! Just pushed 0.6.1 to pypi.
