### ISSUE TITLE
out of date docs still hanging around

### ISSUE THREAD

**Issue by matsen** [fhcrc/seqmagick#60]
Note that there are two copies of out of date docs on the web:

- http://pythonhosted.org/seqmagick/
- https://fhcrc.github.io/seqmagick/index.html

**Comment by nhoffman** [comment]
GH Pages are up to date as of 0.7.0 (https://fhcrc.github.io/seqmagick/) - the release instructions in DEVELOPING.rst include a reminder to update docs there.

Looks like pythonhosted is deprecated in favor of readthedocs: https://github.com/pypa/pypi-legacy/issues/672 - I used the "DESTROY any existing documentation hosted at http://pythonhosted.org/seqmagick" button on pypi to remove.

Not sure how readthedocs is updated - I'd suggest a note there about how to do so.

**Comment by matsen** [comment]
![image](https://user-images.githubusercontent.com/112708/34642472-91655c3a-f2c8-11e7-923a-3a6af609c3de.png)

@nhoffman  If you make an account I can add you as an owner so you can fiddle. Or should I reset the build?

**Comment by nhoffman** [comment]
@matsen Sure, I can try to fix it if you make me an account - looks like it's going to need updating to python3 anyway.

**Comment by nhoffman** [comment]
Ha, sorry: I created an account as "nhoffman"

**Comment by matsen** [comment]
Added you https://readthedocs.org/projects/seqmagick/

**Comment by nhoffman** [comment]
Ok, RTD is up to date.

**Comment by matsen** [comment]
@nhoffman -- we need to update the acknowledgements to include you and Chris!

**Comment by nhoffman** [comment]
Ah, thanks! At the moment CONTRIB just points to https://github.com/fhcrc/seqmagick/graphs/contributors, which is pretty ok, but I suppose it would ne nice (for all of the contributors) add a list in the readme or docs.

**Comment by matsen** [comment]
I'd just add you to https://github.com/fhcrc/seqmagick/blob/94f63844ccd1524b33a4618a44b69cd6e5728053/docs/index.rst "Acknowledgements" but I don't know how you want to be named. Hoffman group? Link?
