### ISSUE TITLE
Deduplication using seqmagick

### ISSUE THREAD

**Issue by dot4822** [fhcrc/seqmagick#69]
To whom it may concern,

I am trying seqmagick to deduplicate nucleotide alignment in fasta file. However, I can only make "--deduplicate-sequences" work for deduplication in place. Since I would like to write all the unique alignments out into another file, I tried "--deduplicated-sequences-file", but it will generate empty file, or file only contaning sequence IDs.

If it is possible, could you give me an example about these deduplication options?

Regards,
Dot

**Comment by matsen** [comment]
Have you tried `seqmagick convert`?

**Comment by dot4822** [comment]
Thanks for your quick responce.

Yes. I tried to use seqmagick convert with "--deduplicated-sequences-file", but it did not work. I'll try to use seqmagick covert with "--deduplicate-sequences" now to see what will happen.

Regards,
Dot

**Comment by matsen** [comment]
For your application you just need `seqmagick convert --deduplicate-sequences original.fasta deduped.fasta`. Let us know if you have difficulty doing that.
